name: ci
on: [pull_request, push]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12, 14, 16, 17]
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
      - run: npm run test:test262
